// Auto-generated from deployment.json — update when contracts are redeployed
export const CONTRACT_IDS = {
  userRegistry: 'CAFHDYYSSR7A5MRMTNY457HDDBBWYJZAQNZ22NT7TOMMBRSNC2OOBYHA',
  socialGraph: 'CCI7DBNILBDTLR2KF24I7647H5JGUSMEJDHXS6D7H6GPSQ3WEBJMUPM7',
  messages: 'CATLF3WXUG3GMD2J4XIOIYVE3ND7PBFYYXHPS4632ZXEPJPNGYNAEZK7',
} as const;
