// Testnet contract addresses (from deployment.json)
export const CONTRACT_IDS = {
  userRegistry: process.env.NEXT_PUBLIC_CONTRACT_USER_REGISTRY ?? 'CDHJHY3LQWJM3PPKGFA6QRDUK2JQU5DQEBFKL42I3UEZNNM6IRFF76DJ',
  socialGraph: process.env.NEXT_PUBLIC_CONTRACT_SOCIAL_GRAPH ?? 'CC3SRPHPKC4WIEJUSQY5KKUSHCBO2Y77VDXIDRKX6XVZLHKTIOQEPULK',
  messages: process.env.NEXT_PUBLIC_CONTRACT_MESSAGES ?? 'CB6A3AMUSDIH7KKZRQ4Y2MT6PSBFQPJND5T5USLQJGTQAPTQ4IIX3QEE',
} as const;
